//------------------ category types-------------

export const REQUEST_FETCHDATA = "REQUEST_FETCHDATA";
export const RECEIVE_FETCHDATA = "RECEIVE_FETCHDATA";

export const REQUEST_DELETE = "REQUEST_DELETE";
export const RECEIVE_DELETE = "RECEIVE_DELETE";

export const REQUEST_ADD_DATA = "REQUEST_ADD_DATA";
export const RECEIVE_ADD_DATA = "RECEIVE_ADD_DATA";

export const REQUEST_EDIT_DATA = "REQUEST_EDIT_DATA";
export const RECEIVE_EDIT_DATA = "RECEIVE_EDIT_DATA";

//------------------ author types-------------

export const REQUEST_AUTHOR_DATA = "REQUEST_AUTHOR_DATA";
export const RECEIVE_AUTHOR_DATA = "RECEIVE_AUTHOR_DATA";

export const REQUEST_DELETE_AUTHOR = "REQUEST_DELETE_AUTHOR";
export const RECEIVE_DELETE_AUTHOR = "RECEIVE_DELETE_AUTHOR";

export const REQUEST_ADD_AUTHOR = "REQUEST_ADD_AUTHOR";
export const RECEIVE_ADD_AUTHOR = "RECEIVE_ADD_AUTHOR";

export const REQUEST_EDIT_AUTHOR = "REQUEST_EDIT_AUTHOR";
export const RECEIVE_EDIT_AUTHOR = "RECEIVE_EDIT_AUTHOR";

//-----------------books add types----------------------------

export const REQUEST_SUBJECT_DATA = "REQUEST_SUBJECT_DATA";
export const RECEIVE_SUBJECT_DATA = "RECEIVE_SUBJECT_DATA";

export const REQUEST_GENRE_DATA = "REQUEST_GENRE_DATA";
export const RECEIVE_GENRE_DATA = "RECEIVE_GENRE_DATA";

export const REQUEST_CLASS_DATA = "REQUEST_CLASS_DATA";
export const RECEIVE_CLASS_DATA = "RECEIVE_CLASS_DATA";

export const REQUEST_EDITBOOK_DATA = "REQUEST_EDITBOOK_DATA";
export const RECEIVE_EDITBOOK_DATA = "RECEIVE_EDITBOOK_DATA";

