//------------------ category types-------------

export const REQUEST_FETCHDATA = "REQUEST_FETCHDATA";
export const RECEIVE_FETCHDATA = "RECEIVE_FETCHDATA";

export const REQUEST_DELETE = "REQUEST_DELETE";
export const RECEIVE_DELETE = "RECEIVE_DELETE";

export const REQUEST_ADD_DATA = "REQUEST_ADD_DATA";
export const RECEIVE_ADD_DATA = "RECEIVE_ADD_DATA";

export const REQUEST_EDIT_DATA = "REQUEST_EDIT_DATA";
export const RECEIVE_EDIT_DATA = "RECEIVE_EDIT_DATA";

//------------------ author types-------------

export const REQUEST_AUTHOR_DATA = "REQUEST_AUTHOR_DATA";
export const RECEIVE_AUTHOR_DATA = "RECEIVE_AUTHOR_DATA";

export const REQUEST_DELETE_AUTHOR = "REQUEST_DELETE_AUTHOR";
export const RECEIVE_DELETE_AUTHOR = "RECEIVE_DELETE_AUTHOR";

export const REQUEST_ADD_AUTHOR = "REQUEST_ADD_AUTHOR";
export const RECEIVE_ADD_AUTHOR = "RECEIVE_ADD_AUTHOR";

export const REQUEST_EDIT_AUTHOR = "REQUEST_EDIT_AUTHOR";
export const RECEIVE_EDIT_AUTHOR = "RECEIVE_EDIT_AUTHOR";

export const REQUEST_FILTER_AUTHOR = "REQUEST_FILTER_AUTHOR";
export const RECEIVE_FILTER_AUTHOR = "RECEIVE_FILTER_AUTHOR";

//-----------------books add types----------------------------

export const REQUEST_BOOK_DATA = "REQUEST_BOOK_DATA";
export const RECEIVE_BOOK_DATA = "RECEIVE_BOOK_DATA";

export const REQUEST_SEARCH_BOOK = "REQUEST_SEARCH_BOOK";
export const RECEIVE_SEARCH_BOOK = "RECEIVE_SEARCH_BOOK";

export const REQUEST_EDITBOOK_DATA = "REQUEST_EDITBOOK_DATA";
export const RECEIVE_EDITBOOK_DATA = "RECEIVE_EDITBOOK_DATA";

//---------------------member types------------------

export const REQUEST_MEMBER_DATA = "REQUEST_MEMBER_DATA";
export const RECEIVE_MEMBER_DATA = "RECEIVE_MEMBER_DATA";

export const REQUEST_SEARCH_MEMBER = "REQUEST_SEARCH_MEMBER";
export const RECEIVE_SEARCH_MEMBER = "RECEIVE_SEARCH_MEMBER";

export const REQUEST_EDIT_MEMBER = "REQUEST_EDIT_MEMBER";
export const RECEIVE_EDIT_MEMBER = "RECEIVE_EDIT_MEMBER";

export const REQUEST_ADD_MEMBER = "REQUEST_ADD_MEMBER";
export const RECEIVE_ADD_MEMBER = "RECEIVE_ADD_MEMBER";

export const REQUEST_DELETE_MEMBER = "REQUEST_DELETE_MEMBER";
export const RECEIVE_DELETE_MEMBER = "RECEIVE_DELETE_MEMBER";


 //---------------------Genre list------------------
 export const REQUEST_FETCHDATA_GENRE = "REQUEST_FETCHDATA_GENRE";
 export const RECEIVE_FETCHDATA_GENRE = "RECEIVE_FETCHDATA_GENRE";
 
 export const REQUEST_DELETE_GENRE = "REQUEST_DELETE_GENRE";
 export const RECEIVE_DELETE_GENRE = "RECEIVE_DELETE_GENRE";
 
 export const REQUEST_ADD_DATA_GENRE = "REQUEST_ADD_DATA_GENRE";
 export const RECEIVE_ADD_DATA_GENRE = "RECEIVE_ADD_DATA_GENRE";
 
 export const REQUEST_EDIT_DATA_GENRE = "REQUEST_EDIT_DATA_GENRE";
 export const RECEIVE_EDIT_DATA_GENRE= "RECEIVE_EDIT_DATA_GENRE";
